package com.lijin.study.springcloud.service.dao.mapper;

import com.lijin.study.springcloud.service.dao.model.Pay;
import com.lijin.study.springcloud.service.dao.model.PayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    long countByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int deleteByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int insert(Pay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int insertSelective(Pay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    List<Pay> selectByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    Pay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int updateByExampleSelective(@Param("row") Pay row, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int updateByExample(@Param("row") Pay row, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int updateByPrimaryKeySelective(Pay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay
     *
     * @mbg.generated Thu Dec 19 21:25:42 CST 2024
     */
    int updateByPrimaryKey(Pay row);
}